name: "[CD] Continuous Delivery"

#Sempre que tiver um commit ou um PR for aberto
#on: 
#  [push]:
#     branches: [main] 
on: 
  [push]

env:
  VERCEL_ORG_ID: H2L9BdPTvuRUAQdFIy3AyhFj
  VERCEL_PROJECT_ID: prj_U4LNEgEO9U8WdyaBEMxZdMXYiXhz

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: "Debug"
        run: |
          ls -la
      - name: "Install Dependencies"
        run: "npm install"
      - name: "Deploy"
        run: "npx vercel --prod"
